export const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    SHOW_CART: 'SHOW_CART',
    HIDE_CART: 'HIDE_CART',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    DECREASE_ITEM: 'DECREASE_ITEM',
};