const ShopActionTypes = {
    // UPDATE_COLLECTIONS: 'UPDATE_COLLECTION',
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAIL: 'FETCH_COLLECTIONS_FAIL'
};

export default ShopActionTypes;